version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: addresses_user
      POSTGRES_PASSWORD: addresses_password
      POSTGRES_DB: addresses
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./:/app:ro

volumes:
  postgres_data:
